name: 'Retrieve Workflow Logs Action'
description: 'Play regex against log file in order to see if error are matched'
inputs:
  github-token:
    description: "Token with access to update message, and read the database"
    required: true
  path-logs:
    description: "Where you want the logs to be stored"
    required: false
    default: process.cwd() + '/logs'
  keep-only-error-files:
    description: "If you want to keep only the files that have errors"
    required: false
    default: true
outputs:
  path-logs:
    description: "The value that you have set as input, or default if not set"
runs:
  using: 'node16'
  main: 'dist/index.js'
