name: pr-validation
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  discussions: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    name: run_lint_on_build_failure_analyser_action
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: set_node.js_16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: install_ncc_modules
        run: npm install ncc
      - name: run_lint
        run: npm run lint
      - name: run_test
        run: npm run test
  integration-tests:
    runs-on: ubuntu-latest
    name: run_integration_test_on_build_failure_analyser_action
    steps:
      - id: generate_path_logs
        run: echo "path_logs=$(echo ${RUNNER_TEMP,,}'/logs.txt')" >> $GITHUB_OUTPUT
